services:
  api:
    image: api
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - backend/.env
    environment:
      - APP_NAME=api
    volumes:
      - ./backend/src:/app/src
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db
  frontend:
    image: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    environment:
      - APP_NAME=frontend
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - api
